# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Unhandled Exceptions
tagline:          'something'
description:      'Ramblings, interrupted'

author:
  name:           'Vedang Naik'
  url:            https://github.com/vedangnaik

paginate:         5

plugins: [jekyll-paginate]