# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

kramdown:
  parse_block_html: true

# Setup
title:            Unhandled Exceptions
tagline:          ''
description:      ''

author:
  name:           'Vedang Naik'
  url:            https://github.com/vedangnaik

paginate:         5

plugins: [jekyll-paginate]